# Generated by Django 5.0.6 on 2024-06-20 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address_zip_code'),
    ]

    operations = [
    ]
